set nocompatible
source $VIMRUNTIME/mswin.vim
behave mswin

" needs to have Hack font installed on your system
set guifont=Hack:h12:cANSI

source $VIMRUNTIME/settings.vim
source $VIMRUNTIME/mappings.vim

filetype off "required for vundle to work

source $VIMRUNTIME/bundles.vim

filetype plugin indent on
